{
  "uid": "b4cde99af0a5dfab",
  "name": "加法无效场景：$%%^&*+0",
  "fullName": "计算器实战L2.Test#test_add_error",
  "historyId": "c94b9f434438af2010b453bf68c65940",
  "time": {
    "start": 1708153312532,
    "stop": 1708153312533,
    "duration": 1
  },
  "description": "\n        计算器进阶功能的无效用例。\n        使用数据参数化的方法,调用getdate函数获取用例的参数。\n        步骤一：\n        计算a+b\n        步骤二：\n        断言a+b==c\n        因为输入中a或者b中包含一些无效的非整数输入，\n        所以用例将会失败。用xfail进行标记。\n        ",
  "descriptionHtml": "<pre><code>    计算器进阶功能的无效用例。\n    使用数据参数化的方法,调用getdate函数获取用例的参数。\n    步骤一：\n    计算a+b\n    步骤二：\n    断言a+b==c\n    因为输入中a或者b中包含一些无效的非整数输入，\n    所以用例将会失败。用xfail进行标记。\n</code></pre>\n",
  "status": "skipped",
  "statusMessage": "XFAIL\n\nTypeError: '>' not supported between instances of 'str' and 'int'",
  "statusTrace": "self = <计算器实战L2.Test object at 0x03536A90>, a = '$%%^&*', b = 0, c = 'TypeError'\n\n    @pytest.mark.advtest\n    @allure.severity(allure.severity_level.MINOR)\n    @allure.story('加法无效场景')\n    @allure.feature('加法功能')\n    @pytest.mark.xfail\n    @allure.title(\"加法无效场景：{a}+{b}\")\n    @pytest.mark.parametrize(\"a, b, c\", getdate('加法e.yaml'))\n    def test_add_error(self, a, b, c):\n        \"\"\"\n        计算器进阶功能的无效用例。\n        使用数据参数化的方法,调用getdate函数获取用例的参数。\n        步骤一：\n        计算a+b\n        步骤二：\n        断言a+b==c\n        因为输入中a或者b中包含一些无效的非整数输入，\n        所以用例将会失败。用xfail进行标记。\n        \"\"\"\n        tester = Calculator()\n        with allure.step('测试步骤一,尝试进行计算'):\n>           sum = tester.add(a, b)\n\n计算器实战L2.py:163: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <计算器实战L2.Calculator object at 0x035AA330>, a = '$%%^&*', b = 0\n\n    def add(self, a, b):\n>       if a > 99 or a < -99 or b > 99 or b < -99:\nE       TypeError: '>' not supported between instances of 'str' and 'int'\n\n计算器实战L2.py:45: TypeError",
  "flaky": false,
  "newFailed": false,
  "beforeStages": [],
  "testStage": {
    "description": "\n        计算器进阶功能的无效用例。\n        使用数据参数化的方法,调用getdate函数获取用例的参数。\n        步骤一：\n        计算a+b\n        步骤二：\n        断言a+b==c\n        因为输入中a或者b中包含一些无效的非整数输入，\n        所以用例将会失败。用xfail进行标记。\n        ",
    "status": "skipped",
    "statusMessage": "XFAIL\n\nTypeError: '>' not supported between instances of 'str' and 'int'",
    "statusTrace": "self = <计算器实战L2.Test object at 0x03536A90>, a = '$%%^&*', b = 0, c = 'TypeError'\n\n    @pytest.mark.advtest\n    @allure.severity(allure.severity_level.MINOR)\n    @allure.story('加法无效场景')\n    @allure.feature('加法功能')\n    @pytest.mark.xfail\n    @allure.title(\"加法无效场景：{a}+{b}\")\n    @pytest.mark.parametrize(\"a, b, c\", getdate('加法e.yaml'))\n    def test_add_error(self, a, b, c):\n        \"\"\"\n        计算器进阶功能的无效用例。\n        使用数据参数化的方法,调用getdate函数获取用例的参数。\n        步骤一：\n        计算a+b\n        步骤二：\n        断言a+b==c\n        因为输入中a或者b中包含一些无效的非整数输入，\n        所以用例将会失败。用xfail进行标记。\n        \"\"\"\n        tester = Calculator()\n        with allure.step('测试步骤一,尝试进行计算'):\n>           sum = tester.add(a, b)\n\n计算器实战L2.py:163: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <计算器实战L2.Calculator object at 0x035AA330>, a = '$%%^&*', b = 0\n\n    def add(self, a, b):\n>       if a > 99 or a < -99 or b > 99 or b < -99:\nE       TypeError: '>' not supported between instances of 'str' and 'int'\n\n计算器实战L2.py:45: TypeError",
    "steps": [
      {
        "name": "测试步骤一,尝试进行计算",
        "time": {
          "start": 1708153312532,
          "stop": 1708153312532,
          "duration": 0
        },
        "status": "broken",
        "statusMessage": "TypeError: '>' not supported between instances of 'str' and 'int'\n",
        "statusTrace": "  File \"E:\\霍格沃茨学社\\Hogwarts-Studies\\homework\\pytest_and_allure\\计数器实战L2\\计算器实战L2.py\", line 163, in test_add_error\n    sum = tester.add(a, b)\n          ^^^^^^^^^^^^^^^^\n  File \"E:\\霍格沃茨学社\\Hogwarts-Studies\\homework\\pytest_and_allure\\计数器实战L2\\计算器实战L2.py\", line 45, in add\n    if a > 99 or a < -99 or b > 99 or b < -99:\n       ^^^^^^\n",
        "steps": [],
        "attachments": [],
        "parameters": [],
        "attachmentsCount": 0,
        "shouldDisplayMessage": true,
        "stepsCount": 0,
        "hasContent": true
      }
    ],
    "attachments": [],
    "parameters": [],
    "attachmentsCount": 0,
    "shouldDisplayMessage": true,
    "stepsCount": 1,
    "hasContent": true
  },
  "afterStages": [],
  "labels": [
    {
      "name": "epic",
      "value": "计算器需求"
    },
    {
      "name": "feature",
      "value": "加法功能"
    },
    {
      "name": "severity",
      "value": "minor"
    },
    {
      "name": "story",
      "value": "加法无效场景"
    },
    {
      "name": "tag",
      "value": "@pytest.mark.xfail"
    },
    {
      "name": "tag",
      "value": "advtest"
    },
    {
      "name": "suite",
      "value": "计算器实战L2"
    },
    {
      "name": "subSuite",
      "value": "Test"
    },
    {
      "name": "host",
      "value": "ZJS-E14"
    },
    {
      "name": "thread",
      "value": "20200-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "计算器实战L2"
    },
    {
      "name": "resultFormat",
      "value": "allure2"
    }
  ],
  "parameters": [
    {
      "name": "a",
      "value": "'$%%^&*'"
    },
    {
      "name": "b",
      "value": "0"
    },
    {
      "name": "c",
      "value": "'TypeError'"
    }
  ],
  "links": [],
  "hidden": false,
  "retry": false,
  "extra": {
    "severity": "minor",
    "retries": [],
    "categories": [],
    "tags": [
      "@pytest.mark.xfail",
      "advtest"
    ]
  },
  "source": "b4cde99af0a5dfab.json",
  "parameterValues": [
    "'$%%^&*'",
    "0",
    "'TypeError'"
  ]
}