{
  "uid": "d7a1551b25ad1522",
  "name": "除法无效用例:hello/$%%^&*",
  "fullName": "计算器实战L2.Test#test_div_error",
  "historyId": "a972d3f145ca8be54d4e6519ac7ee68b",
  "time": {
    "start": 1708153312842,
    "stop": 1708153312842,
    "duration": 0
  },
  "description": "\n        计算器进阶功能的无效用例。\n        使用数据参数化的方法,调用getdate函数获取用例的参数。\n        步骤一：\n        计算a/b\n        步骤二：\n        断言a/b==c\n        因为输入中a或者b中包含一些无效的非整数输入，\n        所以用例将会失败。用xfail进行标记。\n        ",
  "descriptionHtml": "<pre><code>    计算器进阶功能的无效用例。\n    使用数据参数化的方法,调用getdate函数获取用例的参数。\n    步骤一：\n    计算a/b\n    步骤二：\n    断言a/b==c\n    因为输入中a或者b中包含一些无效的非整数输入，\n    所以用例将会失败。用xfail进行标记。\n</code></pre>\n",
  "status": "skipped",
  "statusMessage": "XFAIL\n\nTypeError: '>' not supported between instances of 'str' and 'int'",
  "statusTrace": "self = <计算器实战L2.Test object at 0x0353F390>, a = 'hello', b = '$%%^&*'\nc = 'TypeError'\n\n    @pytest.mark.advtest\n    @allure.severity(allure.severity_level.MINOR)\n    @allure.story('除法无效场景')\n    @allure.feature('除法功能')\n    @pytest.mark.xfail\n    @pytest.mark.parametrize(\"a, b, c\", getdate('除法e.yaml'))\n    def test_div_error(self, a, b, c):\n        \"\"\"\n        计算器进阶功能的无效用例。\n        使用数据参数化的方法,调用getdate函数获取用例的参数。\n        步骤一：\n        计算a/b\n        步骤二：\n        断言a/b==c\n        因为输入中a或者b中包含一些无效的非整数输入，\n        所以用例将会失败。用xfail进行标记。\n        \"\"\"\n        tester = Calculator()\n        # 动态更新用例标题，可以参与到用例执行中去增加当前用例的标题名\n        allure.dynamic.title(f\"除法无效用例:{a}/{b}\")\n        with allure.step('测试步骤一,尝试进行计算'):\n>           sum = tester.div(a, b)\n\n计算器实战L2.py:189: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <计算器实战L2.Calculator object at 0x035A84B0>, a = 'hello', b = '$%%^&*'\n\n    def div(self, a, b):\n>       if a > 99 or a < -99 or b > 99 or b < -99:\nE       TypeError: '>' not supported between instances of 'str' and 'int'\n\n计算器实战L2.py:52: TypeError",
  "flaky": false,
  "newFailed": false,
  "beforeStages": [],
  "testStage": {
    "description": "\n        计算器进阶功能的无效用例。\n        使用数据参数化的方法,调用getdate函数获取用例的参数。\n        步骤一：\n        计算a/b\n        步骤二：\n        断言a/b==c\n        因为输入中a或者b中包含一些无效的非整数输入，\n        所以用例将会失败。用xfail进行标记。\n        ",
    "status": "skipped",
    "statusMessage": "XFAIL\n\nTypeError: '>' not supported between instances of 'str' and 'int'",
    "statusTrace": "self = <计算器实战L2.Test object at 0x0353F390>, a = 'hello', b = '$%%^&*'\nc = 'TypeError'\n\n    @pytest.mark.advtest\n    @allure.severity(allure.severity_level.MINOR)\n    @allure.story('除法无效场景')\n    @allure.feature('除法功能')\n    @pytest.mark.xfail\n    @pytest.mark.parametrize(\"a, b, c\", getdate('除法e.yaml'))\n    def test_div_error(self, a, b, c):\n        \"\"\"\n        计算器进阶功能的无效用例。\n        使用数据参数化的方法,调用getdate函数获取用例的参数。\n        步骤一：\n        计算a/b\n        步骤二：\n        断言a/b==c\n        因为输入中a或者b中包含一些无效的非整数输入，\n        所以用例将会失败。用xfail进行标记。\n        \"\"\"\n        tester = Calculator()\n        # 动态更新用例标题，可以参与到用例执行中去增加当前用例的标题名\n        allure.dynamic.title(f\"除法无效用例:{a}/{b}\")\n        with allure.step('测试步骤一,尝试进行计算'):\n>           sum = tester.div(a, b)\n\n计算器实战L2.py:189: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <计算器实战L2.Calculator object at 0x035A84B0>, a = 'hello', b = '$%%^&*'\n\n    def div(self, a, b):\n>       if a > 99 or a < -99 or b > 99 or b < -99:\nE       TypeError: '>' not supported between instances of 'str' and 'int'\n\n计算器实战L2.py:52: TypeError",
    "steps": [
      {
        "name": "测试步骤一,尝试进行计算",
        "time": {
          "start": 1708153312842,
          "stop": 1708153312842,
          "duration": 0
        },
        "status": "broken",
        "statusMessage": "TypeError: '>' not supported between instances of 'str' and 'int'\n",
        "statusTrace": "  File \"E:\\霍格沃茨学社\\Hogwarts-Studies\\homework\\pytest_and_allure\\计数器实战L2\\计算器实战L2.py\", line 189, in test_div_error\n    sum = tester.div(a, b)\n          ^^^^^^^^^^^^^^^^\n  File \"E:\\霍格沃茨学社\\Hogwarts-Studies\\homework\\pytest_and_allure\\计数器实战L2\\计算器实战L2.py\", line 52, in div\n    if a > 99 or a < -99 or b > 99 or b < -99:\n       ^^^^^^\n",
        "steps": [],
        "attachments": [],
        "parameters": [],
        "attachmentsCount": 0,
        "shouldDisplayMessage": true,
        "stepsCount": 0,
        "hasContent": true
      }
    ],
    "attachments": [],
    "parameters": [],
    "attachmentsCount": 0,
    "shouldDisplayMessage": true,
    "stepsCount": 1,
    "hasContent": true
  },
  "afterStages": [],
  "labels": [
    {
      "name": "feature",
      "value": "除法功能"
    },
    {
      "name": "epic",
      "value": "计算器需求"
    },
    {
      "name": "story",
      "value": "除法无效场景"
    },
    {
      "name": "severity",
      "value": "minor"
    },
    {
      "name": "tag",
      "value": "@pytest.mark.xfail"
    },
    {
      "name": "tag",
      "value": "advtest"
    },
    {
      "name": "suite",
      "value": "计算器实战L2"
    },
    {
      "name": "subSuite",
      "value": "Test"
    },
    {
      "name": "host",
      "value": "ZJS-E14"
    },
    {
      "name": "thread",
      "value": "20200-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "计算器实战L2"
    },
    {
      "name": "resultFormat",
      "value": "allure2"
    }
  ],
  "parameters": [
    {
      "name": "a",
      "value": "'hello'"
    },
    {
      "name": "b",
      "value": "'$%%^&*'"
    },
    {
      "name": "c",
      "value": "'TypeError'"
    }
  ],
  "links": [],
  "hidden": false,
  "retry": false,
  "extra": {
    "severity": "minor",
    "retries": [],
    "categories": [],
    "tags": [
      "@pytest.mark.xfail",
      "advtest"
    ]
  },
  "source": "d7a1551b25ad1522.json",
  "parameterValues": [
    "'hello'",
    "'$%%^&*'",
    "'TypeError'"
  ]
}